mkdir fluent-logging
cd fluent-logging
mkdir simulator
mkdir book
cd simulator 
wget https://github.com/mp3monster/LogGenerator/archive/master.zip
unzip master.zip
rm master.zip
cd ../book
wget https://github.com/mp3monster/LoggingInActionWithFluentd/archive/public.zip
unzip public.zip
rm public.zip
